version: "3"

volumes:
  dbbackups:
  postgis-data:
  tarantool:

services:
  main_service:
    image: main_service
    ports:
      - "8000:8000"
    volumes:
      - $PWD/media:/dripapp/media
    depends_on:
      - tarantool
      - postgres

  # chat_service:
  #   image: chat_service
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - $PWD/media:/dripapp/media
  #   depends_on:
  #     - tarantool
  #     - postgres

  auth_service:
    image: auth_service
    ports:
      - "8002:8002"
      - "8003:8003"
    volumes:
      - $PWD/media:/dripapp/media
    depends_on:
      - tarantool
      - postgres

  tarantool:
    image: "drip_tarantool"
    ports:
      - "3301:3301"
    volumes:
      - tarantool:/var/lib/tarantool
    #   - $PWD/docker/tarantool_scripts/dripapp.lua:/opt/tarantool/dripapp.lua

  postgres:
    image: postgres:latest
    volumes:
      - postgis-data:/var/lib/postgresql
      - $PWD/docker/postgres_scripts/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    # env_file:
    #   - envs/postgres.env
    environment:
        POSTGRES_DB: "drip"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "lolkek"
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
      
  node-exporter:
      image: prom/node-exporter
      restart: always
      ports:
        - "9100:9100"
      volumes:
        - ./monitoring:/etc/config

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus:/etc/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    user: "grafana"
    depends_on:
      - prometheus
    ports:
      - 3000:3000