// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE7177167DecodeDripappInternalMicroservicesChatModels(in *jlexer.Lexer, out *Hub) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE7177167EncodeDripappInternalMicroservicesChatModels(out *jwriter.Writer, in Hub) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Hub) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE7177167EncodeDripappInternalMicroservicesChatModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Hub) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE7177167EncodeDripappInternalMicroservicesChatModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Hub) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE7177167DecodeDripappInternalMicroservicesChatModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Hub) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE7177167DecodeDripappInternalMicroservicesChatModels(l, v)
}
