// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "dripapp/internal/microservices/auth/models"

	mock "github.com/stretchr/testify/mock"
)

// SessionUsecase is an autogenerated mock type for the SessionUsecase type
type SessionUsecase struct {
	mock.Mock
}

// AddSession provides a mock function with given fields: c, session
func (_m *SessionUsecase) AddSession(c context.Context, session models.Session) error {
	ret := _m.Called(c, session)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Session) error); ok {
		r0 = rf(c, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSession provides a mock function with given fields: c
func (_m *SessionUsecase) DeleteSession(c context.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
