// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "dripapp/internal/dripapp/models"

	mock "github.com/stretchr/testify/mock"
)

// SessionManager is an autogenerated mock type for the SessionManager type
type SessionManager struct {
	mock.Mock
}

// DeleteSessionCookie provides a mock function with given fields: sessionCookie
func (_m *SessionManager) DeleteSessionCookie(sessionCookie string) error {
	ret := _m.Called(sessionCookie)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sessionCookie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSessionByCookie provides a mock function with given fields: _a0
func (_m *SessionManager) GetSessionByCookie(_a0 string) (models.Session, error) {
	ret := _m.Called(_a0)

	var r0 models.Session
	if rf, ok := ret.Get(0).(func(string) models.Session); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Session)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsSessionByCookie provides a mock function with given fields: sessionCookie
func (_m *SessionManager) IsSessionByCookie(sessionCookie string) bool {
	ret := _m.Called(sessionCookie)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(sessionCookie)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewSessionCookie provides a mock function with given fields: sessionCookie, id
func (_m *SessionManager) NewSessionCookie(sessionCookie string, id uint64) error {
	ret := _m.Called(sessionCookie, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uint64) error); ok {
		r0 = rf(sessionCookie, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
